### PR TITLE
Fix water issue on 2fort

### PR DESCRIPTION
**Pull request by iraizo**
This pr includes: 
 - Nav mesh deletion near the water
 - Nav mesh deletion near the bridge polls
 - Prevents the bots from jumping into the water and doing it in a loop

### CODE REVIEW

**Comment by Freezgam03** [comment]
As far as I remember there were no problems with the bots jumping down from the top ledge (not bridge) and into the water. Having no way of quickly getting down there for the navbot to e.g. get health from the sewers or kill a enemy when it's coming from the top seems unpractical and makes the bot not as efficient.

**Comment by iraizo** [comment]
> As far as I remember there were no problems with the bots jumping down from the top ledge (not bridge) and into the water. Having no way of quickly getting down there for the navbot to e.g. get health from the sewers or kill a enemy when it's coming from the top seems unpractical and makes the bot not as efficient.
> 
> As I am no longer on Linux anymore, I can't really test this with the new navbot therefore I need your confirmation that you tried everything you could to see if you could get a working way down from the ledge into the water without the navbot "looping" in the water after it jumped down (not from the bridge).

The issue is that 2 meshes (screenshot 1) are connected between the water and the ground making the bot want to go into the water (no enemies near the water or sewers). In screenshot 2 i deleted the meshes near the posts to make the bots go more into the center because some (rarely) get stuck or slowly move across, ive tested this for 2 days now and they seem perfectly fine, and if they see a player down there they will just walk down there which isnt really non efficent other than the normal behavior i was seeing with the bots jumping down the water

**Comment by Freezgam03** [comment]
> 
> and if they see a player down there they will just walk down there which isnt really non efficent other than the normal behavior i was seeing with the bots jumping down the water

Looking at the Navmesh though, I don't see any navmesh areas that connect down into the water area directly? So the only way down there would be to walk down the stairs that you find in both of the bases

**Comment by iraizo** [comment]
> Looking at the Navmesh though, I don't see any navmesh areas that connect down into the water area directly? So the only way down there would be to walk down the stairs that you find in both of the bases

Im not able to get a screenshot right now, but download the ctf_2fort.nav from the current main repo, and look at it like screenshot 1, you will see 2 nav meshes connected, probaly in blue and red.

**Comment by Freezgam03** [comment]
> Im not able to get a screenshot right now, but download the ctf_2fort.nav from the current main repo, and look at it like screenshot 1, you will see 2 nav meshes connected, probaly in blue and red.

Yes, I made that as the older navbot wasn't able to directly jump down into the water, so I made a temp work around by creating a floating navmesh area that the navbot would recognize and then be able to drop down without issues.

**Comment by iraizo** [comment]
> Yes, I made that as the older navbot wasn't able to directly jump down into the water, so I made a temp work around by creating a floating navmesh area that the navbot would recognize and then be able to drop down without issues.

Yes, but the problem is that the bot does that constantly which decreases efficency and theres no way that many people are in the sewers, else the bot could just take the stairs

**Comment by Freezgam03** [comment]
> Yes, but the problem is that the bot does that constantly which decreases efficency and theres no way that many people are in the sewers, else the bot could just take the stairs

Unless behaviour was changed or something recently, I never saw bots drop into the water unless they avoided sentries by going through the sewers, get health or fight a enemy down in the sewers.

**Comment by iraizo** [comment]
> > Yes, but the problem is that the bot does that constantly which decreases efficency and theres no way that many people are in the sewers, else the bot could just take the stairs
> 
> Unless behaviour was changed or something recently, I never saw bots drop into the water unless they avoided sentries by going through the sewers, get health or fight a enemy down in the sewers.

Not sure what to say here, try it out, load 5 bots on ctf_2fort in casual and see what they do, you will see them drop into the water for some idiotic reason when there are 5 players in arms reach

**Comment by BenCat07** [comment]
> > > Yes, but the problem is that the bot does that constantly which decreases efficency and theres no way that many people are in the sewers, else the bot could just take the stairs
> > 
> > 
> > Unless behaviour was changed or something recently, I never saw bots drop into the water unless they avoided sentries by going through the sewers, get health or fight a enemy down in the sewers.
> 
> Not sure what to say here, try it out, load 5 bots on ctf_2fort in casual and see what they do, you will see them drop into the water for some idiotic reason when there are 5 players in arms reach

sniper bots will generally not run at them ever

**Comment by iraizo** [comment]
> sniper bots will generally not run at them ever

Yeah, this is why i removed their only option of not actually killing the enemy

**Comment by iraizo** [comment]
> It's not all sniper bots though, when making navmesh changes you have to think of all possible bots. Therefore the change seems not good, as it hurts every other bot besides sniper maybe. The actual change/bugfix that should be made is to the Sniper Navbot running into enemies when there below the bot, or at a lower level basically.

Im not sure how any other class could profit from dropping down there

**Comment by Freezgam03** [comment]
> Im not sure how any other class could profit from dropping down there

- Scout bots reacting to people being in the sewers while being near the bridge, getting behind them
- Soldier bots being able to in emergency drop down to quickly get health rather than walk all the way back in the base
- In case of getting shot they can go down there if they really want to opening another escape route for bots

**Pull request closed without merging**
